apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local-lib.name" . }}-app
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  message: "Hello from app"
  {{- include "app.myCustomFunction" . | nindent 2 }}
